apiVersion: apps/v1
kind: Deployment
metadata:
  name: mystrom-exporter
  namespace: mystrom-exporter
  labels:
    app: mystrom-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mystrom-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mystrom-exporter
        framework: spring
    spec:
      containers:
        - image: robachmann/mystrom-exporter:1.1.1-arm64
          name: mystrom-exporter
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              memory: 512Mi
          env:
            - name: "JAVA_OPTS"
              value: "-XX:ReservedCodeCacheSize=64M -XX:MaxDirectMemorySize=128M"
            - name: "MYSTROM_TARGETS_0_ADDRESS"
              value: "10.35.55.58"
            - name: "MYSTROM_TARGETS_0_ALIAS"
              value: "Office"
            - name: "MYSTROM_TARGETS_1_ADDRESS"
              value: "10.35.55.59"
            - name: "MYSTROM_TARGETS_1_ALIAS"
              value: "Living Room"
            - name: "MYSTROM_TIMEZONE"
              value: "Europe/Zurich"
            - name: "MYSTROM_OFFPEAK_DAY"
              value: "SUNDAY"
            - name: "MYSTROM_OFFPEAK_START_HOUR"
              value: "22"
            - name: "MYSTROM_OFFPEAK_START_MINUTE"
              value: "0"
            - name: "MYSTROM_OFFPEAK_END_HOUR"
              value: "7"
            - name: "MYSTROM_OFFPEAK_END_MINUTE"
              value: "0"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 10
