apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mystrom-exporter
  namespace: mystrom-exporter
  labels:
    release: prometheus
spec:
  jobLabel: mystrom-exporter
  selector:
    matchLabels:
      exporter: mystrom
  namespaceSelector:
    matchNames:
      - mystrom-exporter
  endpoints:
    - port: http-metrics
      interval: 5m
      path: /metrics
